// 1-
INSERT INTO PRODUCTOS (PRODUCTO, NOMBRE, PRECIO)
VALUES (1, "TV", 4000),
(2, "COMPUTADORA", 1500),
(3, "CELULAR", 2000),
(4, "TABLET", 2000);

INSERT INTO CAJEROS (CAJERO, NOM_APELS)
VALUES (1, "JOAQUIN"),
(2, "JOSE"),
(3, "MANUEL");

INSERT INTO MAQUINAS_REGISTRADORAS (MAQUINA, PISO)
VALUES (1, 10),
(2, 18),
(3, 16);


INSERT INTO VENTA (CAJERO, MAQUINA, PRODUCTO)
VALUES (2, 1, 1),
(3, 1, 1),
(2, 1, 2);
(2, 1, 3);
(1, 1, 4);
(1, 1, 4);
(1, 1, 3);
(3, 1, 2);


// 2- 
SELECT P.PRODUCTO, COUNT(P.PRODUCTO) AS VENTAS FROM PRODUCTOS P
INNER JOIN VENTA V
ON P.PRODUCTO = V.PRODUCTO
GROUP BY P.PRODUCTO
ORDER BY VENTAS DESC;

// 3-
SELECT C.NOM_APELS as CAJERO, P.NOMBRE, P.PRECIO, M.PISO FROM VENTA V
INNER JOIN CAJEROS C
ON V.CAJERO = C.CAJERO
INNER JOIN PRODUCTOS P
ON V.PRODUCTO = P.PRODUCTO
INNER JOIN MAQUINAS_REGISTRADORAS M
ON M.MAQUINA = V.MAQUINA;

// 4-
SELECT M.PISO, COUNT(M.MAQUINA) AS VENTAS FROM MAQUINAS_REGISTRADORAS M 
INNER JOIN VENTA V
ON M.MAQUINA = V.MAQUINA
GROUP BY M.PISO;

// 5- 
SELECT C.CAJERO, C.NOM_APELS, SUM(P.PRECIO) AS IMPORTE_TOTAL FROM CAJEROS C
INNER JOIN VENTA V 
ON C.CAJERO = V.CAJERO
INNER JOIN PRODUCTOS P
ON P.PRODUCTO = V.PRODUCTO
GROUP BY C.CAJERO;

// 6-
SELECT C.CAJERO, C.NOM_APELS FROM CAJEROS C
INNER JOIN VENTA V
ON C.CAJERO = V.CAJERO
INNER JOIN MAQUINAS_REGISTRADORAS M
ON M.MAQUINA = V.MAQUINA
WHERE M.PISO IN (
SELECT M.PISO FROM MAQUINAS_REGISTRADORAS M
INNER JOIN VENTA V 
ON V.MAQUINA = M.MAQUINA
INNER JOIN PRODUCTOS P
ON P.PRODUCTO = V.PRODUCTO
GROUP BY M.PISO
HAVING SUM(P.PRECIO) < 5000
)
GROUP BY C.CAJERO;